project_id = "arqfzzracvkgkazxlkcb"

[functions.create-user]
verify_jwt = false

[functions.telegram-send-otp]
verify_jwt = false

[functions.telegram-verify-otp]
verify_jwt = false

[functions.telegram-verify-2fa]
verify_jwt = false
